//! Embedded gateway-admin asset table and lookup.
//!
//! The table itself is generated by `build.rs` into `$OUT_DIR` as
//! `EMBEDDED_WEB_FILES: &[(&str, &[u8])]` — one entry per file under
//! `apps/gateway-admin/out`, keyed by its forward-slash relative path. When the
//! frontend bundle was not built the table is empty.

use std::path::{Path, PathBuf};

use crate::fs_assets::sanitize_relative_path;

// Generated by `build.rs`: `EMBEDDED_WEB_FILES: &[(&str, &[u8])]`, one entry per
// file in `apps/gateway-admin/out` (forward-slash relative path → bytes). Empty
// when the frontend bundle was not built.
include!(concat!(env!("OUT_DIR"), "/embedded_web_assets.rs"));

/// Look up an embedded asset by its forward-slash relative path.
#[must_use]
pub fn embedded_asset(relative: &str) -> Option<&'static [u8]> {
    EMBEDDED_WEB_FILES
        .iter()
        .find(|(path, _)| *path == relative)
        .map(|(_, bytes)| *bytes)
}

/// Iterate every embedded asset's forward-slash relative path.
pub fn embedded_asset_paths() -> impl Iterator<Item = &'static str> {
    EMBEDDED_WEB_FILES.iter().map(|(path, _)| *path)
}

/// Whether the embedded SPA entry point (`index.html`) is present. A `false`
/// result means the frontend bundle was not built into this binary.
#[must_use]
pub fn embedded_assets_available() -> bool {
    embedded_asset("index.html").is_some()
}

fn embedded_asset_path(request_path: &str) -> PathBuf {
    let relative = sanitize_relative_path(request_path);
    if relative.as_os_str().is_empty() {
        PathBuf::from("index.html")
    } else {
        relative
    }
}

fn embedded_lookup_key(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// Resolve `request_path` against the embedded bundle, returning the asset bytes
/// and the resolved relative path (used by the caller to derive headers).
///
/// Lookup order matches the previous Labby handler: the exact sanitized path,
/// then `<path>/index.html`, then the root `index.html` SPA fallback. Returns
/// `None` when nothing matches (including an empty embedded bundle).
#[must_use]
pub fn resolve_embedded_asset(request_path: &str) -> Option<(&'static [u8], PathBuf)> {
    let relative = embedded_asset_path(request_path);
    if let Some(bytes) = embedded_asset(&embedded_lookup_key(&relative)) {
        return Some((bytes, relative));
    }

    let index_path = relative.join("index.html");
    if let Some(bytes) = embedded_asset(&embedded_lookup_key(&index_path)) {
        return Some((bytes, index_path));
    }

    embedded_asset("index.html").map(|bytes| (bytes, PathBuf::from("index.html")))
}
