use std::fmt::Write as _;

use clap::CommandFactory;
use serde::Serialize;

use crate::catalog::ParamEntry;

use super::types::{
    ActionDoc, EnvDoc, FeatureDoc, FeatureMatrix, ParamDoc, RouteDoc, ServiceDoc,
    SurfaceAvailability,
};

pub fn json<T: Serialize>(value: &T) -> anyhow::Result<String> {
    Ok(format!("{}\n", serde_json::to_string_pretty(value)?))
}

pub fn mcp_help(catalog: &crate::catalog::Catalog) -> String {
    let mut out = header("mcp-help", "labby docs generate");
    out.push_str("| Service | Category | Status | Action | Destructive | Params | Returns |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
    for service in &catalog.services {
        for action in &service.actions {
            writeln!(
                out,
                "| {} | {} | {} | {} | {} | {} | {} |",
                code(&service.name),
                cell(&service.category),
                cell(&service.status),
                code(&action.name),
                action.destructive,
                params_cell(&action.params),
                code(&action.returns)
            )
            .ok();
        }
    }
    out
}

pub fn cli_help() -> String {
    let mut out = String::from("# Lab CLI Help\n\n");
    out.push_str(
        "Generated by `labby docs generate` from clap command definitions. Do not edit by hand.\n\n",
    );
    let mut command = crate::cli::Cli::command();
    write_cli_command(&mut out, &mut command, "labby");
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

pub fn service_catalog(services: &[ServiceDoc]) -> String {
    let mut out = header("service-catalog", "labby docs generate");
    out.push_str("| Service | Status | Exposure | Feature | Category | Surfaces | Metadata |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
    for service in services {
        writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} |",
            code(&service.name),
            cell(&service.status),
            cell(&format!("{:?}", service.exposure)),
            cell(&opt(service.feature.as_deref())),
            cell(&service.category),
            cell(&surfaces(&service.surfaces)),
            cell(&service.metadata_source)
        )
        .ok();
    }
    out
}

pub fn env_reference(vars: &[EnvDoc]) -> String {
    let mut out = header("env-reference", "labby docs generate");
    out.push_str("| Service | Env Var | Required | Secret | Example | Description |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for var in vars {
        writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} |",
            code(&var.service),
            code(&var.env_var),
            var.required,
            var.secret,
            code(&var.example),
            cell(&var.description)
        )
        .ok();
    }
    out
}

pub fn action_catalog(actions: &[ActionDoc]) -> String {
    let mut out = header("action-catalog", "labby docs generate");
    out.push_str(
        "This is a global inventory, not the active runtime exposure or authorization policy.\n\n",
    );
    out.push_str("| Service | Action | Built-in | Destructive | Params | Returns | Surfaces |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
    for action in actions {
        writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} |",
            code(&action.service),
            code(&action.action),
            action.builtin,
            action.destructive,
            params_cell(&action.params),
            code(&action.returns),
            cell(&surfaces(&action.surface_availability))
        )
        .ok();
    }
    out
}

pub fn feature_matrix(matrix: &FeatureMatrix) -> String {
    let mut out = header("feature-matrix", "labby docs generate");
    if matrix.mismatches.is_empty() {
        out.push_str("Feature invariant status: clean.\n\n");
    } else {
        out.push_str("Feature invariant mismatches:\n\n");
        for mismatch in &matrix.mismatches {
            writeln!(
                out,
                "- {}: {}",
                code(&mismatch.feature),
                cell(&mismatch.message)
            )
            .ok();
        }
        out.push('\n');
    }
    out.push_str("| Crate | Feature | Class | In Default | In All | Maps To | Dependencies |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
    for feature in &matrix.features {
        write_feature_row(&mut out, feature);
    }
    out
}

pub fn api_routes(routes: &[RouteDoc]) -> String {
    let mut out = header("api-routes", "labby docs generate");
    out.push_str(
        "| Method | Path | Auth | Session | CSRF | Host Validation | Master | Group | Notes |\n",
    );
    out.push_str("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for route in routes {
        writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} |",
            cell(&route.method),
            code(&route.path),
            route.auth_required,
            route.session_cookie_allowed,
            route.csrf_required,
            route.host_validation,
            route.master_only,
            cell(&route.handler_group),
            cell(&route.notes)
        )
        .ok();
    }
    out
}
pub fn generated_readme() -> String {
    let mut out = String::from("# Generated Docs\n\n");
    out.push_str("Files in this directory are generated from code-owned metadata.\n\n");
    out.push_str("Regenerate all artifacts with:\n\n```bash\njust docs-generate\n```\n\n");
    out.push_str("Verify tracked artifacts are fresh with:\n\n```bash\njust docs-check\n```\n\n");
    out.push_str("`docs-check` compares the declared generated artifact manifest and enforces generated-doc invariants such as feature-matrix consistency and safety linting. It does not run Markdown link checks, live service health, or onboarding audit policy gates.\n\n");
    out.push_str("| Artifact | Source |\n| --- | --- |\n");
    for artifact in [
        "service-catalog.md/json",
        "action-catalog.md/json",
        "env-reference.md/json",
        "api-routes.md/json",
        "openapi.json",
        "feature-matrix.md/json",
        "mcp-help.md/json",
        "cli-help.md",
    ] {
        writeln!(out, "| `{artifact}` | `labby docs generate` |").ok();
    }
    out
}

fn header(name: &str, command: &str) -> String {
    format!(
        "# {}\n\nGenerated by `{}`. Do not edit by hand.\n\n",
        name, command
    )
}

fn write_cli_command(out: &mut String, command: &mut clap::Command, path: &str) {
    writeln!(out, "## `{path}`\n\n```text").ok();
    let help = command.render_long_help().to_string();
    for line in help.trim_end().lines() {
        out.push_str(line.trim_end());
        out.push('\n');
    }
    out.pop();
    out.push_str("\n```\n\n");

    let subcommands = command
        .get_subcommands()
        .map(|subcommand| subcommand.get_name().to_string())
        .collect::<Vec<_>>();
    for name in subcommands {
        if let Some(subcommand) = command.find_subcommand_mut(&name) {
            write_cli_command(out, subcommand, &format!("{path} {name}"));
        }
    }
}

fn write_feature_row(out: &mut String, feature: &FeatureDoc) {
    writeln!(
        out,
        "| {} | {} | {} | {} | {} | {} | {} |",
        cell(&feature.crate_name),
        code(&feature.feature),
        cell(&format!("{:?}", feature.classification)),
        feature.included_in_default,
        feature.included_in_all,
        cell(&opt(feature.mapped_crate_feature.as_deref())),
        feature
            .dependencies
            .iter()
            .map(|dep| code(dep))
            .collect::<Vec<_>>()
            .join("<br>")
    )
    .ok();
}

fn surfaces(surfaces: &SurfaceAvailability) -> String {
    [
        ("cli", surfaces.cli),
        ("mcp", surfaces.mcp),
        ("api", surfaces.api),
        ("web", surfaces.web_ui),
    ]
    .into_iter()
    .filter_map(|(name, enabled)| enabled.then_some(name))
    .collect::<Vec<_>>()
    .join(", ")
}

fn opt(value: Option<&str>) -> String {
    value.unwrap_or("-").to_string()
}

fn cell(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('|', "\\|")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\n', "<br>")
}

fn code(value: &str) -> String {
    format!("`{}`", cell(&value.replace('`', "\\`")))
}

fn params_cell<P: ParamLike>(params: &[P]) -> String {
    params
        .iter()
        .map(|param| {
            let rendered = if param.required() {
                format!("{}*: {}", param.name(), param.ty())
            } else {
                format!("{}: {}", param.name(), param.ty())
            };
            code(&rendered)
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

trait ParamLike {
    fn name(&self) -> &str;
    fn ty(&self) -> &str;
    fn required(&self) -> bool;
}

impl ParamLike for ParamDoc {
    fn name(&self) -> &str {
        &self.name
    }

    fn ty(&self) -> &str {
        &self.ty
    }

    fn required(&self) -> bool {
        self.required
    }
}

impl ParamLike for ParamEntry {
    fn name(&self) -> &str {
        &self.name
    }

    fn ty(&self) -> &str {
        &self.ty
    }

    fn required(&self) -> bool {
        self.required
    }
}

impl ParamLike for lab_apis::core::action::ParamSpec {
    fn name(&self) -> &str {
        self.name
    }

    fn ty(&self) -> &str {
        self.ty
    }

    fn required(&self) -> bool {
        self.required
    }
}
