#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-bytestash"
CONFIG_FILE="$CONFIG_DIR/config.env"

sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  local key="$1"
  local value="$2"
  [[ -z "$value" ]] && return 0
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "bytestash: refusing to write ${key}; value contains a newline" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$(sq "$value")"
}

if [[ -f "$HOME/.lab/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$HOME/.lab/.env"
  set +a
fi

url="${CLAUDE_PLUGIN_OPTION_BYTESTASH_URL:-${BYTESTASH_URL:-}}"
username="${CLAUDE_PLUGIN_OPTION_BYTESTASH_USERNAME:-${BYTESTASH_USERNAME:-}}"
password="${CLAUDE_PLUGIN_OPTION_BYTESTASH_PASSWORD:-${BYTESTASH_PASSWORD:-}}"
token="${CLAUDE_PLUGIN_OPTION_BYTESTASH_TOKEN:-${BYTESTASH_TOKEN:-}}"
api_key="${CLAUDE_PLUGIN_OPTION_BYTESTASH_API_KEY:-${BYTESTASH_API_KEY:-}}"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

umask 177
{
  echo "# Generated by the ByteStash plugin hook. Do not edit by hand."
  write_var "BYTESTASH_URL" "${url%/}"
  write_var "BYTESTASH_USERNAME" "$username"
  write_var "BYTESTASH_PASSWORD" "$password"
  write_var "BYTESTASH_TOKEN" "$token"
  write_var "BYTESTASH_API_KEY" "$api_key"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [[ -z "$url" ]]; then
  echo "bytestash: config written, but BYTESTASH_URL is not configured yet" >&2
  exit 0
fi

echo "bytestash: config written to $CONFIG_FILE"
