mod catalog;
mod client;
pub(crate) mod config;
mod config_mutation;
pub mod discovery;
mod dispatch;
mod index;
pub mod manager;
pub mod oauth;
mod oauth_lifecycle;
mod params;
mod projection;
pub(crate) mod protected_routes;
mod runtime;
mod service_catalog;
mod shared;
pub(crate) mod types;
mod view_models;
mod virtual_servers;

pub use catalog::ACTIONS;
pub use client::{current_gateway_manager, install_gateway_manager};
pub use dispatch::{dispatch, dispatch_with_manager};
pub(crate) use shared::SHARED_GATEWAY_OAUTH_SUBJECT;
