#!/usr/bin/env bash
# SessionStart / ConfigChange hook for the uptime-kuma plugin.
#
# Bridges userConfig -> a fixed-path env file the skill can read. This is
# REQUIRED: empirically, Claude Code injects CLAUDE_PLUGIN_OPTION_* only into
# plugin subprocesses (hooks like this one, MCP, LSP) — NOT into the agent's
# Bash tool that runs the skill's curl. So the hook materializes the config to
# a 600-mode file at a stable path the skill sources. Read-only; writes only
# that file, changes no server state.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-uptime-kuma"
CONFIG_FILE="${CONFIG_DIR}/config.env"

URL="${CLAUDE_PLUGIN_OPTION_UPTIME_KUMA_URL:-}"
KEY="${CLAUDE_PLUGIN_OPTION_UPTIME_KUMA_METRICS_API_KEY:-}"
SLUG="${CLAUDE_PLUGIN_OPTION_UPTIME_KUMA_STATUS_SLUG:-}"

for v in "$URL" "$KEY" "$SLUG"; do
  case "$v" in
    *$'\n'* | *$'\r'*)
      echo "uptime-kuma: config values must not contain newlines" >&2
      exit 2
      ;;
  esac
done

if [ -z "$URL" ]; then
  echo "uptime-kuma: not configured yet (set the Uptime Kuma URL in plugin settings)." >&2
  exit 0
fi
URL="${URL%/}"

sq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }
mkdir -p "$CONFIG_DIR"; chmod 700 "$CONFIG_DIR" 2>/dev/null || true
umask 177
{
  echo "# Generated by the uptime-kuma plugin hook. Do not edit by hand."
  echo "UPTIME_KUMA_URL=$(sq "$URL")"
  echo "UPTIME_KUMA_METRICS_API_KEY=$(sq "$KEY")"
  echo "UPTIME_KUMA_STATUS_SLUG=$(sq "$SLUG")"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

checked=0
if [ -n "$KEY" ]; then
  checked=1
  if curl -fsS --connect-timeout 3 --max-time 8 -u ":${KEY}" "${URL}/metrics" >/dev/null 2>&1; then
    echo "uptime-kuma: /metrics reachable, API key accepted at ${URL}; config written to ${CONFIG_FILE}"
  else
    echo "WARNING: uptime-kuma /metrics at ${URL} unreachable or API key rejected (config written anyway)." >&2
  fi
fi
if [ -n "$SLUG" ]; then
  checked=1
  if curl -fsS --connect-timeout 3 --max-time 8 "${URL}/api/status-page/${SLUG}" >/dev/null 2>&1; then
    echo "uptime-kuma: status page '${SLUG}' reachable at ${URL}"
  else
    echo "WARNING: uptime-kuma status page '${SLUG}' not reachable at ${URL}." >&2
  fi
fi
if [ "$checked" -eq 0 ]; then
  echo "uptime-kuma: config written to ${CONFIG_FILE}. Set a metrics API key and/or status-page slug to enable read access." >&2
fi
