#!/usr/bin/env bash
# SessionStart / ConfigChange hook for the navidrome plugin.
#
# Bridges userConfig -> a fixed-path env file the skill can read. This is
# REQUIRED: empirically, Claude Code injects CLAUDE_PLUGIN_OPTION_* only into
# plugin subprocesses (hooks like this one, MCP, LSP) — NOT into the agent's
# Bash tool that runs the skill's curl. So the hook materializes the config to
# a 600-mode file at a stable path the skill sources. Writes only that file;
# changes no server state.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-navidrome"
CONFIG_FILE="${CONFIG_DIR}/config.env"

URL="${CLAUDE_PLUGIN_OPTION_NAVIDROME_URL:-}"
USER_NAME="${CLAUDE_PLUGIN_OPTION_NAVIDROME_USERNAME:-}"
PASS="${CLAUDE_PLUGIN_OPTION_NAVIDROME_PASSWORD:-}"

# Reject control-character injection in configured values.
for v in "$URL" "$USER_NAME" "$PASS"; do
  case "$v" in
    *$'\n'* | *$'\r'*)
      echo "navidrome: config values must not contain newlines" >&2
      exit 2
      ;;
  esac
done

if [ -z "$URL" ] || [ -z "$USER_NAME" ] || [ -z "$PASS" ]; then
  echo "navidrome: not configured yet (set Navidrome URL, username, password in plugin settings)." >&2
  exit 0
fi
URL="${URL%/}"

# Materialize config the skill will source. Single-quote values so the skill's
# shell treats them literally (passwords often contain $, !, &, etc.).
sq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }
mkdir -p "$CONFIG_DIR"; chmod 700 "$CONFIG_DIR" 2>/dev/null || true
umask 177
{
  echo "# Generated by the navidrome plugin hook. Do not edit by hand."
  echo "NAVIDROME_URL=$(sq "$URL")"
  echo "NAVIDROME_USERNAME=$(sq "$USER_NAME")"
  echo "NAVIDROME_PASSWORD=$(sq "$PASS")"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

# Connectivity + credential check (read-only).
if command -v md5sum >/dev/null 2>&1 && command -v openssl >/dev/null 2>&1; then
  salt="$(openssl rand -hex 8)"
  token="$(printf '%s%s' "$PASS" "$salt" | md5sum | cut -d' ' -f1)"
  resp="$(curl -fsS --connect-timeout 3 --max-time 8 \
    "${URL}/rest/ping.view?u=${USER_NAME}&t=${token}&s=${salt}&v=1.16.1&c=lab&f=json" 2>/dev/null || true)"
  case "$resp" in
    *'"status":"ok"'*)     echo "navidrome: connected to ${URL} (auth OK); config written to ${CONFIG_FILE}" ;;
    *'"status":"failed"'*) echo "WARNING: navidrome reachable at ${URL} but auth failed — check username/password." >&2 ;;
    *)                     echo "WARNING: navidrome at ${URL} not reachable; config written to ${CONFIG_FILE} anyway." >&2 ;;
  esac
else
  echo "navidrome: config written to ${CONFIG_FILE} (openssl+md5sum missing, skipped connectivity check)."
fi
