#!/usr/bin/env bash
# SessionStart / ConfigChange hook for the arrs plugin.
#
# Bridges userConfig -> a 600-mode env file the skills source. Required because
# Claude Code injects CLAUDE_PLUGIN_OPTION_* only into plugin subprocesses (this
# hook), NOT into the agent's Bash tool that runs the skills' curl. The userConfig
# keys are named to match the env-var names the skills already use, so this just
# re-exports every CLAUDE_PLUGIN_OPTION_<NAME> as <NAME> in the file.
# Writes only that file; touches no service.
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-arrs"
CONFIG_FILE="${CONFIG_DIR}/config.env"

mkdir -p "$CONFIG_DIR"; chmod 700 "$CONFIG_DIR" 2>/dev/null || true
umask 177
tmp="${CONFIG_FILE}.tmp.$$"
echo "# Generated by the arrs plugin hook ($(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo now)). Do not edit by hand." > "$tmp"

count=0
# Re-export every userConfig value (CLAUDE_PLUGIN_OPTION_<NAME>) as <NAME>.
while IFS='=' read -r name value; do
  case "$name" in
    CLAUDE_PLUGIN_OPTION_*) ;;
    *) continue ;;
  esac
  key="${name#CLAUDE_PLUGIN_OPTION_}"
  [ -n "$value" ] || continue
  case "$value" in
    *$'\n'* | *$'\r'*) echo "arrs: ${key} contains a newline; skipping" >&2; continue ;;
  esac
  # single-quote the value, escaping any embedded single quotes
  esc=$(printf '%s' "$value" | sed "s/'/'\\\\''/g")
  printf "%s='%s'\n" "$key" "$esc" >> "$tmp"
  count=$((count + 1))
done < <(env)

mv "$tmp" "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [ "$count" -eq 0 ]; then
  echo "arrs: no services configured yet — set service URLs/keys in the plugin settings." >&2
else
  echo "arrs: wrote ${count} settings to ${CONFIG_FILE}"
fi
