//! Action catalog for the `setup` Bootstrap orchestrator.

use lab_apis::core::action::{ActionSpec, ParamSpec};

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        returns: "Schema",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "state",
        description: "First-run + draft snapshot for the wizard / settings UI",
        destructive: false,
        returns: "SetupSnapshot",
        params: &[],
    },
    ActionSpec {
        name: "schema.get",
        description: "UiSchema projection for all (or filtered) services",
        destructive: false,
        returns: "ServiceSchemaMap",
        params: &[ParamSpec {
            name: "services",
            ty: "string[]",
            required: false,
            description: "Optional filter; defaults to every service in the registry",
        }],
    },
    ActionSpec {
        name: "draft.get",
        description: "Read .env.draft with secret values masked to '***'",
        destructive: false,
        returns: "DraftEntry[]",
        params: &[],
    },
    ActionSpec {
        name: "draft.set",
        description: "Write a key (or section) into .env.draft (validated server-side)",
        destructive: false,
        returns: "DraftSetOutcome",
        params: &[
            ParamSpec {
                name: "entries",
                ty: "DraftEntry[]",
                required: true,
                description: "Key/value pairs to write into the draft",
            },
            ParamSpec {
                name: "force",
                ty: "boolean",
                required: false,
                description: "Overwrite conflicting draft keys (default false)",
            },
        ],
    },
    ActionSpec {
        name: "draft.commit",
        description: "Run audit and atomically merge .env.draft into .env",
        destructive: true,
        returns: "CommitOutcome",
        params: &[ParamSpec {
            name: "force",
            ty: "boolean",
            required: false,
            description: "Overwrite conflicting .env keys (default false)",
        }],
    },
    ActionSpec {
        name: "settings.state",
        description: "Return non-secret operator settings and runtime service policy state",
        destructive: false,
        returns: "SettingsState",
        params: &[],
    },
    ActionSpec {
        name: "settings.update",
        description: "Update non-secret operator settings with validation",
        destructive: true,
        returns: "SettingsState",
        params: &[ParamSpec {
            name: "services.built_in_upstream_apis_enabled",
            ty: "boolean",
            required: true,
            description: "Enable built-in upstream API service integrations",
        }],
    },
    ActionSpec {
        name: "plugin_hook",
        description: "Run binary-owned local setup checks for Claude plugin hooks",
        destructive: true,
        returns: "SetupReport",
        params: &[ParamSpec {
            name: "repair",
            ty: "boolean",
            required: false,
            description: "Create missing local Lab setup files; defaults to true",
        }],
    },
    ActionSpec {
        name: "check",
        description: "Check local Lab setup prerequisites without mutating the filesystem",
        destructive: false,
        returns: "SetupReport",
        params: &[],
    },
    ActionSpec {
        name: "repair",
        description: "Repair missing local Lab setup prerequisites without contacting external services",
        destructive: true,
        returns: "SetupReport",
        params: &[],
    },
    ActionSpec {
        name: "installed_plugins",
        description: "List installed Claude Code lab plugins",
        destructive: false,
        returns: "InstalledPlugin[]",
        params: &[ParamSpec {
            name: "force",
            ty: "boolean",
            required: false,
            description: "Bypass the short in-process cache",
        }],
    },
    ActionSpec {
        name: "services_status",
        description: "Join service configuration, draft, and Claude plugin state",
        destructive: false,
        returns: "ServiceStatus[]",
        params: &[],
    },
    ActionSpec {
        name: "install_plugin",
        description: "Install the Claude Code plugin for one configured service",
        destructive: true,
        returns: "PluginMutationResult",
        params: &[ParamSpec {
            name: "service",
            ty: "string",
            required: true,
            description: "Registered service name",
        }],
    },
    ActionSpec {
        name: "uninstall_plugin",
        description: "Uninstall the Claude Code plugin for one service",
        destructive: true,
        returns: "PluginMutationResult",
        params: &[ParamSpec {
            name: "service",
            ty: "string",
            required: true,
            description: "Registered service name",
        }],
    },
    ActionSpec {
        name: "finalize",
        description: "Alias for draft.commit; same params, same returns",
        destructive: true,
        returns: "CommitOutcome",
        params: &[ParamSpec {
            name: "force",
            ty: "boolean",
            required: false,
            description: "Overwrite conflicting .env keys (default false)",
        }],
    },
];
