//! Embeds the built gateway-admin web UI (`apps/gateway-admin/out`) into the
//! binary as a `&[(&str, &[u8])]` table written to `OUT_DIR/web_assets.rs`.
//!
//! Why a build script instead of `include_dir!`: `include_dir!` is a *procedural*
//! macro that walks the asset directory during macro expansion, which runs inside
//! rustc. Under sccache-dist that expansion happens on a remote build server whose
//! sandbox does not contain `apps/gateway-admin/out` (it lives outside the crate
//! source tree and is never shipped), so the macro panics
//! (`include_dir!(...) ... is not a directory` / "Job failed on server"). A build
//! script runs locally, copies the assets into `OUT_DIR`, and emits builtin
//! `include_bytes!` calls, which are dist-compatible.
//!
//! If the asset directory is absent (the frontend has not been built), an empty
//! table is generated and the build still succeeds — the runtime degrades
//! gracefully via `embedded_web_assets_available()`.

use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let assets_src = Path::new(&manifest_dir).join("../../apps/gateway-admin/out");

    // Re-run when the asset root changes (added/removed files change its mtime).
    println!("cargo:rerun-if-changed={}", assets_src.display());

    let dest_root = out_dir.join("web-assets");
    // Start clean so removed source files do not linger in OUT_DIR.
    if dest_root.exists() {
        fs::remove_dir_all(&dest_root).expect("clear OUT_DIR/web-assets");
    }

    let mut entries: Vec<String> = Vec::new();
    if assets_src.is_dir() {
        fs::create_dir_all(&dest_root).expect("create OUT_DIR/web-assets");
        collect(&assets_src, &assets_src, &dest_root, &mut entries);
    }
    entries.sort();

    let mut code = String::from(
        "// @generated by build.rs — embedded gateway-admin web assets.\n\
         static EMBEDDED_WEB_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for rel in &entries {
        // Per-file re-run so content edits (not just add/remove) regenerate.
        println!("cargo:rerun-if-changed={}", assets_src.join(rel).display());
        // `include_bytes!` reads from the remote's OUT_DIR at compile time, so the
        // copied bytes travel with the distributed job rather than the (absent)
        // source tree. Asset paths are web filenames (no quotes/backslashes), so
        // direct interpolation into the string literal is safe.
        code.push_str(&format!(
            "    ({rel:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/web-assets/{rel}\"))),\n"
        ));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("web_assets.rs"), code).expect("write OUT_DIR/web_assets.rs");
}

/// Recursively copy every file under `dir` into `dest_root`, recording each
/// asset's `/`-separated path relative to `base`.
fn collect(base: &Path, dir: &Path, dest_root: &Path, out: &mut Vec<String>) {
    for entry in fs::read_dir(dir).expect("read_dir asset directory") {
        let path = entry.expect("read asset dir entry").path();
        if path.is_dir() {
            collect(base, &path, dest_root, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(base)
                .expect("asset path under base")
                .to_string_lossy()
                .replace('\\', "/");
            let dest = dest_root.join(&rel);
            if let Some(parent) = dest.parent() {
                fs::create_dir_all(parent).expect("create asset parent dir in OUT_DIR");
            }
            fs::copy(&path, &dest).expect("copy asset into OUT_DIR");
            out.push(rel);
        }
    }
}
