#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lab-memos"
CONFIG_FILE="$CONFIG_DIR/config.env"

sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_var() {
  local key="$1"
  local value="$2"
  [[ -z "$value" ]] && return 0
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "memos: refusing to write ${key}; value contains a newline" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$(sq "$value")"
}

if [[ -f "$HOME/.lab/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$HOME/.lab/.env"
  set +a
fi

url="${CLAUDE_PLUGIN_OPTION_MEMOS_URL:-${MEMOS_URL:-}}"
token="${CLAUDE_PLUGIN_OPTION_MEMOS_API_TOKEN:-${CLAUDE_PLUGIN_OPTION_MEMOS_TOKEN:-${MEMOS_API_TOKEN:-${MEMOS_TOKEN:-}}}}"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

umask 177
{
  echo "# Generated by the Memos plugin hook. Do not edit by hand."
  write_var "MEMOS_URL" "${url%/}"
  write_var "MEMOS_API_TOKEN" "$token"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

if [[ -z "$url" || -z "$token" ]]; then
  echo "memos: config written, but URL or API token is not configured yet" >&2
  exit 0
fi

echo "memos: config written to $CONFIG_FILE"
